all:
	gcc -Wall -std=gnu11 -o generator generator.c
	gcc -Wall -std=gnu11 -o main1 main1.c -lpthread
	gcc -Wall -std=gnu11 -o main2 main2.c -lpthread
	gcc -Wall -std=gnu11 -o main3 main3.c -lpthread

.PHONY: all
